# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mann_whitney_probs_int <- function(m, n) {
    .Call('_DiscreteTests_mann_whitney_probs_int', PACKAGE = 'DiscreteTests', m, n)
}

